const movies = [
  {
    id: 761053,
    backdrop_path: "/fQq1FWp1rC89xDrRMuyFJdFUdMd.jpg",
    genre_ids: [10749, 35],
    overview:
      "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
    poster_path: "/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg",
    release_date: "2020-11-19",
    vote_average: 9,
    title: "Gabriel's Inferno Part III",
    inWatchList: false,
    trailer: "mjPUGem9SaY",
  },
  {
    id: 724089,
    backdrop_path: "/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
    genre_ids: [10749],
    overview:
      "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
    poster_path: "/pci1ArYW7oJ2eyTo2NMYEKHHiCP.jpg",
    release_date: "2020-07-31",
    vote_average: 8.8,
    title: "Gabriel's Inferno Part II",
    inWatchList: false,
    trailer: "5g02v1oz5Y0",
  },
  {
    id: 441130,
    backdrop_path: "/mxn0RJ6stopje13MZdwU35XDnAx.jpg",
    genre_ids: [10751, 12, 16, 14],
    overview:
      "In a time of superstition and magic, when wolves are seen as demonic and nature an evil to be tamed, a young apprentice hunter comes to Ireland with her father to wipe out the last pack. But when she saves a wild native girl, their friendship leads her to discover the world of the Wolfwalkers and transform her into the very thing her father is tasked to destroy.",
    poster_path: "/ehAKuE48okTuonq6TpsNQj8vFTC.jpg",
    release_date: "2020-10-26",
    vote_average: 8.8,
    title: "Wolfwalkers",
    inWatchList: false,
    trailer: "BL_RH3P6Cz0",
  },
  {
    id: 696374,
    backdrop_path: "/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
    genre_ids: [10749],
    overview:
      "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
    poster_path: "/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
    release_date: "2020-05-29",
    vote_average: 8.7,
    title: "Gabriel's Inferno",
    inWatchList: false,
    trailer: "a581-Vb-nrQ",
  },
  {
    id: 496243,
    backdrop_path: "/ApiBzeaa95TNYliSbQ8pJv4Fje7.jpg",
    genre_ids: [35, 53, 18],
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    vote_average: 8.5,
    title: "Parasite",
    inWatchList: false,
    trailer: "isOGD_7hNIY",
  },
  {
    id: 278,
    backdrop_path: "/tXHpvlr5F7gV5DwgS7M5HBrUi2C.jpg",
    genre_ids: [18, 80],
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    release_date: "1994-09-23",
    vote_average: 8.7,
    title: "The Shawshank Redemption",
    inWatchList: false,
    trailer: "9qqfMvKxBa0",
  },
  {
    id: 238,
    backdrop_path: "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
    genre_ids: [18, 80],
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    vote_average: 8.7,
    title: "The Godfather",
    inWatchList: false,
    trailer: "fBNpSRtfIUA",
  },
  {
    id: 424,
    backdrop_path: "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
    genre_ids: [18, 36, 10752],
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-11-30",
    vote_average: 8.6,
    title: "Schindler's List",
    inWatchList: false,
    trailer: "bJcLRFWxRno",
  },
  {
    id: 372058,
    backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    genre_ids: [10749, 16, 18],
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    release_date: "2016-08-26",
    vote_average: 8.6,
    title: "Your Name.",
    inWatchList: false,
    trailer: "xU47nhruN-Q",
  },
  {
    id: 240,
    backdrop_path: "/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg",
    genre_ids: [18, 80],
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    vote_average: 8.6,
    title: "The Godfather: Part II",
    inWatchList: false,
    trailer: "9O1Iy9od7-A",
  },
  {
    id: 755812,
    backdrop_path: "/yR27bZPIkNhpGEIP3jKV2EifTgo.jpg",
    genre_ids: [16, 10751],
    overview:
      "During a school field trip, Ladybug and Cat Noir meet the American superheroes, whom they have to save from an akumatised super-villain. They discover that Miraculous exist in the United States too.",
    poster_path: "/kIHgjAkuzvKBnmdstpBOo4AfZah.jpg",
    release_date: "2020-09-26",
    vote_average: 8.6,
    title: "Miraculous World: New York, United HeroeZ",
    inWatchList: false,
    trailer: "K41a_JkCM1U",
  },
  {
    id: 572154,
    backdrop_path: "/hQQTE285UQB1lLY1XiioQ77LYnC.jpg",
    genre_ids: [16, 35, 10749, 18, 14],
    overview:
      "In Fujisawa, Sakuta Azusagawa is in his second year of high school. Blissful days with his girlfriend and upperclassman, Mai Sakurajima, are interrupted by the appearance of his first crush, Shoko Makinohara.",
    poster_path: "/7Ai8vNEv4zEveh12JViGikoVPVV.jpg",
    release_date: "2019-06-15",
    vote_average: 8.5,
    title: "Rascal Does Not Dream of a Dreaming Girl",
    inWatchList: false,
    trailer: "UbLBbxSm8hs",
  },
  {
    id: 775996,
    backdrop_path: "/lOSdUkGQmbAl5JQ3QoHqBZUbZhC.jpg",
    genre_ids: [53, 28, 878],
    overview:
      "In the near future, a drone pilot is sent into a deadly militarized zone and must work with an android officer to locate a doomsday device.",
    poster_path: "/e6SK2CAbO3ENy52UTzP3lv32peC.jpg",
    release_date: "2021-01-15",
    vote_average: 6.5,
    title: "Outside the Wire",
    inWatchList: false,
    trailer: "iwYhA5YvdNc",
  },
  {
    id: 464052,
    backdrop_path: "/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
    genre_ids: [14, 28, 12],
    overview:
      "Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
    poster_path: "/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
    release_date: "2020-12-16",
    vote_average: 7,
    title: "Wonder Woman 1984",
    inWatchList: false,
    trailer: "sfM7_JLk-84",
  },
  {
    id: 651571,
    backdrop_path: "/nz8xWrTKZzA5A7FgxaM4kfAoO1W.jpg",
    genre_ids: [878, 28],
    overview:
      "A hardened mechanic must stay awake and maintain an interstellar ark fleeing the dying planet Earth with a few thousand lucky souls on board... the last of humanity. Unfortunately, humans are not the only passengers. A shapeshifting alien creature has taken residence, its only goal is to kill as many people as possible. The crew must think quickly to stop this menace before it destroys mankind.",
    poster_path: "/13B6onhL6FzSN2KaNeQeMML05pS.jpg",
    release_date: "2020-12-17",
    vote_average: 5,
    title: "Breach",
    inWatchList: false,
    trailer: "vntSSo0yuc4",
  },
  {
    id: 508442,
    backdrop_path: "/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg",
    genre_ids: [10751, 16, 35, 18, 10402, 14],
    overview:
      "Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.",
    poster_path: "/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
    release_date: "2020-12-25",
    vote_average: 8.3,
    title: "Soul",
    inWatchList: false,
    trailer: "4TojlZYqPUo",
  },
  {
    id: 560144,
    backdrop_path: "/3ombg55JQiIpoPnXYb2oYdr6DtP.jpg",
    genre_ids: [878, 28],
    overview:
      "When a virus threatens to turn the now earth-dwelling friendly alien hybrids against humans, Captain Rose Corley must lead a team of elite mercenaries on a mission to the alien world in order to save what's left of humanity.",
    poster_path: "/2W4ZvACURDyhiNnSIaFPHfNbny3.jpg",
    release_date: "2020-10-25",
    vote_average: 5.8,
    title: "Skylines",
    inWatchList: false,
    trailer: "MuuqzLwgMhY",
  },
  {
    id: 399566,
    backdrop_path: "/mGJuQwMq1bEboaVTqQAK4p4zQvC.jpg",
    genre_ids: [28, 878],
    overview:
      "In a time when monsters walk the Earth, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.",
    poster_path: "/soM5eNHxxS3a0AqgvDgm2djJXZp.jpg",
    release_date: "2021-03-25",
    vote_average: 0,
    title: "Godzilla vs. Kong",
    inWatchList: false,
    trailer: "odM92ap8_c0",
  },
  {
    id: 581387,
    backdrop_path: "/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg",
    genre_ids: [28, 12, 53],
    overview:
      "Stagnant since 1903, at an elevation of 9000', a volcano erupts on the mythical and majestic Baekdu Mountain.",
    poster_path: "/zoeKREZ2IdAUnXISYCS0E6H5BVh.jpg",
    release_date: "2019-12-19",
    vote_average: 6.8,
    title: "Ashfall",
    inWatchList: false,
    trailer: "MumttfFid_w",
  },
  {
    id: 539885,
    backdrop_path: "/54yOImQgj8i85u9hxxnaIQBRUuo.jpg",
    genre_ids: [28, 80, 18, 53],
    overview:
      "A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.",
    poster_path: "/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg",
    release_date: "2020-07-02",
    vote_average: 5.6,
    title: "Ava",
    inWatchList: false,
    trailer: "ozUuAcGOhPs",
  },
  {
    id: 604822,
    backdrop_path: "/fX8e94MEWSuTJExndVYxKsmA4Hw.jpg",
    genre_ids: [28, 12, 80],
    overview:
      "Covert security company Vanguard is the last hope of survival for an accountant after he is targeted by the world's deadliest mercenary organization.",
    poster_path: "/vYvppZMvXYheYTWVd8Rnn9nsmNp.jpg",
    release_date: "2020-09-30",
    vote_average: 6.7,
    title: "Vanguard",
    inWatchList: false,
    trailer: "GWIamU7vTKo",
  },
  {
    id: 520946,
    backdrop_path: "/7TxeZVg2evMG42p0uSbMJpWNQ8A.jpg",
    genre_ids: [10751, 16, 14],
    overview:
      "Freddy Lupin, heir to a proud family line of werewolves, is in for a shock when on his 14th birthday his first 'warfing' goes awry, turning him into a ferocious poodle. The pack elders give Freddy until the next moonrise to prove he has the heart of a wolf, or risk being cast out forever. With the help of an unlikely ally in a streetwise stray named Batty, Freddy must prove he's 100% Wolf.",
    poster_path: "/2VrvxK4yxNCU6KVgo5TADJeBEQu.jpg",
    release_date: "2020-06-26",
    vote_average: 6.5,
    title: "100% Wolf",
    inWatchList: false,
    trailer: "u4Tf7bLOErI",
  },
  {
    id: 553604,
    backdrop_path: "/2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg",
    genre_ids: [53, 28, 80, 18],
    overview:
      "A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him, he must fight back to clear his name.",
    poster_path: "/zeD4PabP6099gpE0STWJrJrCBCs.jpg",
    release_date: "2020-09-03",
    vote_average: 6.6,
    title: "Honest Thief",
    inWatchList: false,
    trailer: "_TLtcw7ixRc",
  },
  {
    id: 577922,
    backdrop_path: "/wzJRB4MKi3yK138bJyuL9nx47y6.jpg",
    genre_ids: [28, 53, 878],
    overview:
      "Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
    poster_path: "/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
    release_date: "2020-08-22",
    vote_average: 7.3,
    title: "Tenet",
    inWatchList: false,
    trailer: "LdOM0x0XDMo",
  },
  {
    id: 531219,
    backdrop_path: "/8rIoyM6zYXJNjzGseT3MRusMPWl.jpg",
    genre_ids: [10751, 14, 12, 35, 27],
    overview:
      "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
    poster_path: "/b1C0FuXp4wiPmHLVKq4kwtDMgK6.jpg",
    release_date: "2020-10-25",
    vote_average: 6.8,
    title: "Roald Dahl's The Witches",
    inWatchList: false,
    trailer: "9nlhmJF5FNI",
  },
  {
    id: 340102,
    backdrop_path: "/2AFZyra0Ddwl2oBDhClvD1qSIL6.jpg",
    genre_ids: [28, 27, 878],
    overview:
      "Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.",
    poster_path: "/xZNw9xxtwbEf25NYoz52KdbXHPM.jpg",
    release_date: "2020-08-26",
    vote_average: 6.4,
    title: "The New Mutants",
    inWatchList: false,
    trailer: "bu9e410C__I",
  },
  {
    id: 602269,
    backdrop_path: "/vfuzELmhBjBTswXj2Vqxnu5ge4g.jpg",
    genre_ids: [53, 80],
    overview:
      "Deputy Sheriff Joe 'Deke' Deacon joins forces with Sgt. Jim Baxter to search for a serial killer who's terrorizing Los Angeles. As they track the culprit, Baxter is unaware that the investigation is dredging up echoes of Deke's past, uncovering disturbing secrets that could threaten more than his case.",
    poster_path: "/c7VlGCCgM9GZivKSzBgzuOVxQn7.jpg",
    release_date: "2021-01-27",
    vote_average: 6.4,
    title: "The Little Things",
    inWatchList: false,
    trailer: "1HZAnkxdYuA",
  },
  {
    id: 628534,
    backdrop_path: "/wmx5vrNH6GEpv4NLACfibZlA1bq.jpg",
    genre_ids: [80, 18],
    overview:
      "An ambitious Indian driver uses his wit and cunning to escape from poverty and rise to the top. An epic journey based on the New York Times bestseller.",
    poster_path: "/7K4mdWaLGF2F4ASb2L12tlya9c9.jpg",
    release_date: "2021-01-13",
    vote_average: 6.6,
    title: "The White Tiger",
    inWatchList: false,
    trailer: "oM-Nw9XzqVM",
  },
  {
    id: 635302,
    backdrop_path: "/d1sVANghKKMZNvqjW0V6y1ejvV9.jpg",
    genre_ids: [16, 28, 12, 14, 18],
    overview:
      "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
    poster_path: "/yF45egpHwaYLn4jTyZAgk0Cmug9.jpg",
    release_date: "2020-10-16",
    vote_average: 8,
    title: "Demon Slayer: Infinity Train",
    inWatchList: false,
    trailer: "ATJYac_dORw",
  },
  {
    id: 575446,
    backdrop_path: "/qDrtmc5gDOztiH5vvNT0CwgsLVZ.jpg",
    genre_ids: [18],
    overview:
      "In the near future, a popular uprising in Mexico City interrupts a wedding held at the home of a wealthy family. After the riots have been quashed, they discover the bride has gone missing and plea with the military to help locate her.",
    poster_path: "/v6NodCMzqilx0Xw541P65WFnDfE.jpg",
    release_date: "2020-10-22",
    vote_average: 6.6,
    title: "New Order",
    inWatchList: false,
    trailer: "a0tinkp-jQU",
  },
  {
    id: 720026,
    backdrop_path: "/bJCb1wNJ2EMMFIsWeixRlF7XDHA.jpg",
    genre_ids: [27],
    overview:
      "A family of sadistic butchers lives deep in the backcountry. From the dead of winter to the dog days of summer, anyone who crosses their path is dead meat.",
    poster_path: "/xLbuMxKORru3oTlItLBWpI5WJxR.jpg",
    release_date: "2021-01-12",
    vote_average: 6.8,
    title: "Butchers",
    inWatchList: false,
    trailer: "e4f9hOyV23k",
  },
];

export default movies;
